sudo: required
language: python
dist: xenial
matrix:
  include:
  - python: 2.7
    env: PYV=2.7
  - python: 3.4
    env: PYV=3.4
  - python: 3.5
    env: PYV=3.5
  - python: 3.6
    env: PYV=3.6
  - python: 3.7
    env: PYV=3.7
  - python: 3.8
    env: PYV=3.8
  - python: pypy3
    before_install:
    - sudo apt-get install libssl1.1
  - language: generic
    env: PY3=2 PYV=Mac2
    os: osx
    before_install:
    - python2 -m ensurepip
  - language: generic
    os: osx
    env: PY3=3 PYV=Mac3
    addons:
      homebrew:
        packages:
        - python
install: ".ci/travis.sh"
script: python$PY3 setup.py test -c
after_success:
- if [ -n "$PYV" ]; then coveralls; fi
notifications:
  email:
    on_success: change
    on_failure: change
deploy:
  provider: pypi
  user: "__token__"
  distributions: sdist bdist_wheel
  skip_existing: true
  on:
    tags: true
    condition: $PVV = 3.8
  password: $PYPI_TOKEN
